#!/usr/bin/env sh
# Generated by himan-tracker. This script must never block Codex.
TRACKER_PROJECT_DIR='/Users/detao.li/VSCode/Himan/himan-tracker'

if command -v pnpm >/dev/null 2>&1; then
  (cd "$TRACKER_PROJECT_DIR" && pnpm cli collect --agent codex --quiet) >/dev/null 2>&1
fi
exit 0
